site_name: Sanghoon Kim
theme:
  name: null
  custom_dir: "cinder/"
  analytics:
    gtag: G-8XG3Q1RGE7
copyright: 2017-2023 Sanghoon Kim
nav:
  - Home: index.md
  - My Postings: https://blog.seiker.kr
markdown_extensions:
  - pymdownx.tilde:
